CFLAGS += -I/usr/include/python2.6/
CFLAGS += -Wall -Wfatal-errors -Wswitch-default -Wunreachable-code

CFLAGS += $(addprefix -I, $(shell find interfaces -type d))
CFLAGS += $(addprefix -I, $(shell find headers -type d))
CFLAGS += $(addprefix -I, $(shell find modules -type d))

CFLAGS += -DDUMP

LDFLAGS += -Lmodules

COMPONENT=HerpAppC
include $(MAKERULES)
