.PHONY : all clean

TOSSIM_STUFF := $(addprefix simbuild/micaz/, tossim.o sim.o c-support.o)

ifndef TOSROOT
$(error TOSROOT not defined)
endif

CXXFLAGS := -std=c++0x
CPPFLAGS := -I $(TOSROOT)/tos/lib/tossim/
LDFLAGS := -L simbuild/micaz/

all: test

simbuild/micaz/tossim.o:
	$(MAKE) -f Makefile micaz sim

test: $(TOSSIM_STUFF)

clean:
	$(MAKE) -f Makefile clean
	rm -f test.o test
