.phony : all remake clean

ifndef TOSROOT
$(error TOSROOT not defined)
endif

CXXFLAGS := -std=c++0x
CPPFLAGS := -I $(TOSROOT)/tos/lib/tossim/
LDFLAGS := -L simbuild/micaz/

all: test

remake:
	$(MAKE) -f Makefile micaz sim

test: remake $(addprefix simbuild/micaz/, tossim.o sim.o c-support.o)

clean:
	rm -f Test.o Test
